/** Sugerencias geográficas estáticas para Argentina */
export const GEO_SUGGESTIONS: { label: string; sublabel: string }[] = [
  // — CABA / Barrios —
  { label: "Palermo", sublabel: "CABA" },
  { label: "Belgrano", sublabel: "CABA" },
  { label: "Recoleta", sublabel: "CABA" },
  { label: "San Telmo", sublabel: "CABA" },
  { label: "Puerto Madero", sublabel: "CABA" },
  { label: "Retiro", sublabel: "CABA" },
  { label: "Microcentro", sublabel: "CABA" },
  { label: "Caballito", sublabel: "CABA" },
  { label: "Almagro", sublabel: "CABA" },
  { label: "Villa Crespo", sublabel: "CABA" },
  { label: "Flores", sublabel: "CABA" },
  { label: "Boedo", sublabel: "CABA" },
  { label: "Núñez", sublabel: "CABA" },
  { label: "Villa Urquiza", sublabel: "CABA" },
  { label: "Liniers", sublabel: "CABA" },
  { label: "Mataderos", sublabel: "CABA" },
  { label: "Villa del Parque", sublabel: "CABA" },
  { label: "Saavedra", sublabel: "CABA" },
  { label: "Paternal", sublabel: "CABA" },
  { label: "Villa Pueyrredón", sublabel: "CABA" },
  { label: "Chacarita", sublabel: "CABA" },
  { label: "Parque Centenario", sublabel: "CABA" },
  { label: "Once", sublabel: "CABA" },
  { label: "Congreso", sublabel: "CABA" },

  // — GBA —
  { label: "La Plata", sublabel: "Buenos Aires" },
  { label: "Mar del Plata", sublabel: "Buenos Aires" },
  { label: "Quilmes", sublabel: "Buenos Aires" },
  { label: "Lanús", sublabel: "Buenos Aires" },
  { label: "Lomas de Zamora", sublabel: "Buenos Aires" },
  { label: "Avellaneda", sublabel: "Buenos Aires" },
  { label: "San Isidro", sublabel: "Buenos Aires" },
  { label: "Vicente López", sublabel: "Buenos Aires" },
  { label: "Morón", sublabel: "Buenos Aires" },
  { label: "Hurlingham", sublabel: "Buenos Aires" },
  { label: "Tres de Febrero", sublabel: "Buenos Aires" },
  { label: "San Martín", sublabel: "Buenos Aires" },
  { label: "Tigre", sublabel: "Buenos Aires" },
  { label: "Pilar", sublabel: "Buenos Aires" },
  { label: "Luján", sublabel: "Buenos Aires" },
  { label: "Bahía Blanca", sublabel: "Buenos Aires" },
  { label: "Tandil", sublabel: "Buenos Aires" },
  { label: "Zárate", sublabel: "Buenos Aires" },
  { label: "Campana", sublabel: "Buenos Aires" },

  // — Provincias —
  { label: "Córdoba", sublabel: "Provincia" },
  { label: "Rosario", sublabel: "Santa Fe" },
  { label: "Mendoza", sublabel: "Provincia" },
  { label: "Tucumán", sublabel: "Provincia" },
  { label: "Salta", sublabel: "Provincia" },
  { label: "Misiones", sublabel: "Provincia" },
  { label: "Posadas", sublabel: "Misiones" },
  { label: "Corrientes", sublabel: "Provincia" },
  { label: "Chaco", sublabel: "Provincia" },
  { label: "Resistencia", sublabel: "Chaco" },
  { label: "Entre Ríos", sublabel: "Provincia" },
  { label: "Paraná", sublabel: "Entre Ríos" },
  { label: "Formosa", sublabel: "Provincia" },
  { label: "Jujuy", sublabel: "Provincia" },
  { label: "San Salvador de Jujuy", sublabel: "Jujuy" },
  { label: "San Juan", sublabel: "Provincia" },
  { label: "San Luis", sublabel: "Provincia" },
  { label: "Neuquén", sublabel: "Provincia" },
  { label: "Bariloche", sublabel: "Río Negro" },
  { label: "Río Negro", sublabel: "Provincia" },
  { label: "Chubut", sublabel: "Provincia" },
  { label: "Comodoro Rivadavia", sublabel: "Chubut" },
  { label: "Santa Cruz", sublabel: "Provincia" },
  { label: "Río Gallegos", sublabel: "Santa Cruz" },
  { label: "Tierra del Fuego", sublabel: "Provincia" },
  { label: "Ushuaia", sublabel: "Tierra del Fuego" },
  { label: "Catamarca", sublabel: "Provincia" },
  { label: "La Rioja", sublabel: "Provincia" },
  { label: "Santiago del Estero", sublabel: "Provincia" },
  { label: "La Pampa", sublabel: "Provincia" },
  { label: "Santa Rosa", sublabel: "La Pampa" },
];
